// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TurnTable.Api.Data;

#nullable disable

namespace TurnTable.Api.Migrations
{
    [DbContext(typeof(TurnTableDbContext))]
    partial class TurnTableDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TurnTable.Api.Models.Domain.RotationQueueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RotationQueue");
                });

            modelBuilder.Entity("TurnTable.Api.Models.Domain.Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("TurnTable.Api.Models.Domain.Table", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CurrentServerSection")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<string>("PartyName")
                        .HasColumnType("text");

                    b.Property<int?>("PartySize")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SeatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ServerId")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TypeOrShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = "11",
                            CurrentServerSection = "",
                            MaxSeats = 4,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "21",
                            CurrentServerSection = "",
                            MaxSeats = 6,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "31",
                            CurrentServerSection = "",
                            MaxSeats = 6,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "51",
                            CurrentServerSection = "",
                            MaxSeats = 4,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "12",
                            CurrentServerSection = "",
                            MaxSeats = 4,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "22A",
                            CurrentServerSection = "",
                            MaxSeats = 2,
                            Status = "available",
                            TypeOrShape = "square"
                        },
                        new
                        {
                            Id = "22B",
                            CurrentServerSection = "",
                            MaxSeats = 2,
                            Status = "available",
                            TypeOrShape = "square"
                        },
                        new
                        {
                            Id = "32",
                            CurrentServerSection = "",
                            MaxSeats = 5,
                            Status = "available",
                            TypeOrShape = "circle"
                        },
                        new
                        {
                            Id = "52",
                            CurrentServerSection = "",
                            MaxSeats = 4,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "13",
                            CurrentServerSection = "",
                            MaxSeats = 2,
                            Status = "available",
                            TypeOrShape = "square"
                        },
                        new
                        {
                            Id = "23",
                            CurrentServerSection = "",
                            MaxSeats = 5,
                            Status = "available",
                            TypeOrShape = "circle"
                        },
                        new
                        {
                            Id = "33",
                            CurrentServerSection = "",
                            MaxSeats = 2,
                            Status = "available",
                            TypeOrShape = "square"
                        },
                        new
                        {
                            Id = "53",
                            CurrentServerSection = "",
                            MaxSeats = 4,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "15",
                            CurrentServerSection = "",
                            MaxSeats = 4,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "25",
                            CurrentServerSection = "",
                            MaxSeats = 4,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        },
                        new
                        {
                            Id = "35",
                            CurrentServerSection = "",
                            MaxSeats = 2,
                            Status = "available",
                            TypeOrShape = "square"
                        },
                        new
                        {
                            Id = "16",
                            CurrentServerSection = "",
                            MaxSeats = 4,
                            Status = "available",
                            TypeOrShape = "rectangle"
                        });
                });

            modelBuilder.Entity("TurnTable.Api.Models.Domain.WaitlistEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartySize")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuotedWaitInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WaitlistEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
